###########
# site.title

title:    'Cow Slayers'
subtitle: 'CS 175: Malmo Minecraft Project Shooting Cows'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
